bringing master up-to-date in preps for moving development to master (#244)
* update release to 2.1.9-dev

* cannot specify kernel/ramdisk on HVM s3 images

* update release to 2.1.10-dev

* update release to 2.1.11-dev

* update release to 2.1.12-dev

* update release to 2.1.13-dev

* update release to 2.1.14-dev

* update release to 2.1.15-dev

* update release to 2.1.16-dev

* update release to 2.1.17-dev

* update release to 2.1.18-dev

* update release to 2.1.19-dev

* update release to 2.1.20-dev

* update release to 2.1.21-dev

* update release to 2.1.23-dev

* fix cases where bool returned where CommandResult expected
verify that provision scripts in /var/local succeed before declaring Provisioning Succeeded

* update release to 2.1.24-dev

* replace envoy with subprocess so we can watch long running commands
replace @command and @keyval_parse decorator usage with functions so pylint is no longer confused

* update release to 2.1.25-dev

* fix fcntl conflicts from PR #176
fix mount command
fix monitor_command for non-list commands

* update release to 2.1.26-dev

* strip PATH when running inside virtualenv

* debugging for virtualenv sanitize, not quite working

* remove debugging nonsense
use debug log level for STDERR on commands

* update release to 2.1.27-dev

* set environment variables to give provisioning scripts more context.
run both shell and python script in lexical order.

* reverting the finalizer metadata ordering

* set a bunch of AMINATOR environment variables based on arguments passed to aminator

* update release to 2.1.28-dev

* increase volume unmount retires; failure happening more often with Amazon Linux 2014.03

* update release to 2.1.29-dev

* update release to 2.1.30-dev

* make s3 bundle names uniq to prevent parallel aminations colliding on the s3 files names (very hard to debug)

* fix pylint warning

* make verbose log filename unique (in case there are multiple builds for same package simultaneously)

* fix location for manifest in s3 to match the unique name we uploaded

* fix bogus format

* update release to 2.1.31-dev

* need to short circuit /usr/sbin/service on ubuntu to prevent services from automatically
starting at bake time

* update release to 2.1.32-dev

* fix short_circuit code, moved it to BaseDistroPlugin when it should have moved to BaseLinuxDistroPlugin

* update release to 2.1.33-dev

* adding primitive support for docker image creation

* fix syntax errors

* volume need to call cloud to create container

* fix arguments

* need to umount all the docker automatic imports

* might need to makedir before mounting into chroot

* fix import

* fix isdir/isfile

* dont umount /root and aufs mount point

* add preserve-on-error for docker

* need to kill the contianer after we run it so we can modify the container filesystem

* use cp instead of mv for backing up provision files in case
the file was mounted in (ie docker)

* add --image-name option

* retry some docker calls

* add --docker-root option

* fix dup option

* need to set "arch" for default image name format

* add --docker-registry option

* move docker specific code to docker plugin: https://github.com/aminator-plugins/docker-cloud

* remove docker specific settings, moved to plugin

* update release to 2.1.34-dev

* fix provision_config when dst is a symlink:
Traceback (most recent call last):
  File "/apps/python/local/lib/python2.7/site-packages/aminator/util/linux.py", line 366, in install_provision_config
    shutil.copy(dst,backup)
  File "/usr/lib/python2.7/shutil.py", line 117, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory:

* fix syntax error

* update release to 2.1.35-dev

* adding metrics plugin with default no-op logger plugin.
add metrics decorator utilities to count success/failure and timers
decorate various plugin functions to allow metrics collection

* add entry_point registration

* fix syntax

* setup default "metrics" plugin for each environment

* fix bogus attribute name

* fix metrics plugin default per environment
try again on metrics decorators

* fix syntax

* need context object to find the metrics object when wrapping aws objects

* stupid "local variable referenced before assignment" error

* another tweak metrics plugin, make it work
make metrics logger just log to debug

* update release to 2.1.36-dev

* update release to 2.1.37-dev

* add new "lapse" metrics decorator that calls start_timer and stop_timer

* update release to 2.1.38-dev

* fix metric name for boto wrapped metrics

* update release to 2.1.39-dev

* update release to 2.1.40-dev

* fix #187

* update release to 2.1.42-dev

* Convert string formatting to be compatible with Python2.6

* update release to 2.1.43-dev

* add optional --volume-id and --block-device argument to allow for volume pool management external to aminator

* update release to 2.1.44-dev

* update release to 2.1.45-dev

* fix offset on extra "format" call from #192

* update release to 2.1.46-dev

* minor refactor to allow block device plugin to be more easily used in an
external volume pool manager

* update release to 2.1.47-dev

* if --block-device is used dont use flocking, assume external system is handling locking

* update release to 2.1.48-dev

* another fix for --volume-id

* self._volume needs to be set for snapshotting when we use --volume-id

* fix bogus indetation

* update release to 2.1.49-dev

* set max delay for exponential delay on snapshot monitoring
log progress for snapshots

* update release to 2.1.50-dev

* skip finalizing if provisioning fails

* update release to 2.1.51-dev

* fix for PR#199 context.ami.name can never be empty at this point, we just
need to deal with failed provisioning at __exit__

* update release to 2.1.52-dev

* add metrics for the provision scripts

* update release to 2.1.53-dev

* fix #PR201

* update release to 2.1.54-dev

* fix EXDEV error when backing up provision files

* need to remove files out of way for provision files when it fails on EXDEV

* update release to 2.1.55-dev

* add requirements for rpm build

* Add --parition option for linux block device plugin, partition var to all blockdevices, and partition handling to linux volume plugin mounting

* Adjust config reading

* switch class var

* re order

* pin pylint to version that works

* if --enhanced-networking used set sriov_net_support=simple for registered image

* add --enhanced-networking option

* update release to 2.1.57-dev

* fix 'AttributeError: enhanced_networking'

* update release to 2.1.58-dev

* catch exceptions for tagging formats that require missing metadata

* tweak validation script

* force virtualenv 2.7

* force older setuptools, they broke compat again

* try older setuptools

* add debugging

* try addin --no-site-packages to virtualenv

* ignore pylint failures for now

* dont abort on error

* update release to 2.1.60-dev

* validate pkg installed successfully.

* update release to 2.1.61-dev

* use aptitude install instead of aptitude hold, hold seems to have some crazy
but pulling in i386 packages somewhat randomly

* update release to 2.1.62-dev

* wrap apt-get update in a retry in case we encounter metadata mismatch or other probs

* have apt-get update clean first

* use "hold" instead of "install" (again).  install will ignore the currently
installed package when using local install via dpkg and just install the
highest version

* update release to 2.1.63-dev

* change aptitude hold $pkg to aptiude install $pkg=$ver to work around crazy dependency resolution

* update release to 2.1.64-dev

* update release to 2.1.65-dev

* fix #220, remove invalid pbr version, just use git tag

* update release to 2.1.66-dev

* just warn if we fail to short-circuit missing files
fix log.warn => log.warning

* update release to 2.1.67-dev

* have the aptitude provisioner double check that aptitude installed the right package version

* update release to 2.1.68-dev

* figure out the version via dpkg rather than parsing it out of the file name in case there is an epoch in the version

* update release to 2.1.69-dev

* fix syntax error

* update release to 2.1.70-dev

* slight refactor and reconfiguration. Try to consolidate some of the debug logging to avoid repetition, and the bigger change is doing the metadata update for a local install AFTER dpkg -i but before correcting dependencies.

* update release to 2.1.71-dev

* I made a dumb. @classmethod, @staticmethod, and friends need to be the last decorators called

* update release to 2.1.72-dev

* bad call to super()

* re-enable failing on pylint explosions

* unpin pylint, move to a pylintrc, ignore logging-format-interpolation

* ignore the pylint virtualenv dir

* fix pylint errors

* update release to 2.1.73-dev

* flip classmethods back to instance methods for now. the metrics plugin expects to wrap instance methods and have access to instance state like <instance>._config. rather than chase all the cases down, simply revert for now

* update release to 2.1.74-dev

* fix mount for non file/dir files (ie socket files)

* update source formatting for flake8/pep8/pyfmt

* update release to 2.1.75-dev

* change usage of log.exception to log.debug to push stack traces into detailed logs rather than the info we typically surface to users up-front

* fix whitespace to make flake8 happy

* update release to 2.1.76-dev

* update block device plugin to allow one to configure use of minor devices as HVM instances cannot attach devices to minor device numbers

* update .gitignore to ignore flake8 virtualenv
move flake8 config into setup.cfg
make flake8/pep8 happy

* update release to 2.1.77-dev

* Begone, demon!

Bustin' makes me feel good

* better handling of multibyte unicode output (#239)

better handling of multibyte unicode output

* update release to 2.1.80-dev

* update release to 2.1.81.dev

* assume input encoding is utf-8, delay encoding to bytes until after buffers have been built (#240)

* update release to 2.1.82.dev

* update release to 2.1.83.dev

* update release to 2.1.84.dev

* boto.ec2.Volume.delete() simply returns True/False upon success/failure, but spews to ERROR if boto.ec2.Volume.update() is called against a non-existent volume (which ends up dropping an XML error that may confuse end users). Simply rely on Volume.delete() returning True/False and log (to DEBUG for now) if a volume deletion returns False (#242)

* update release to 2.1.85.dev